# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- test
- build
- deploy
mandatory tests:
  stage: test
  before_script:
  - apt-get update -qq && apt-get install -qq --no-install-recommends flake8 shellcheck
  script:
  - make test
extra tests:
  allow_failure: true
  stage: test
  before_script:
  - apt-get update -qq && apt-get install -qq --no-install-recommends --yes ca-certificates
    curl python3-minimal git yamllint shellcheck
  - curl -sS https://raw.githubusercontent.com/Seravo/gnitpick/master/gnitpick.py
    -o /usr/bin/gnitpick; chmod +x /usr/bin/gnitpick
  script:
  - make test-extra
build-app:
  stage: build
  image: node:latest
  cache:
    paths:
    - app/.node_modules
  before_script:
  - npm install -g npm@latest
  - cd app
  - npm install
  script:
  - npm run lint
  - npm run build
  - find dist -ls
staging:
  stage: deploy
  rules:
  - if: $CI_PROJECT_NAMESPACE == "fevermap" && $CI_COMMIT_BRANCH == "master"
  script:
  - which ssh-agent || ( apt-get update -qq && apt-get install -qq openssh-client
    )
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$FEVERMAP_APP_USER_SSH_PRIVATE_KEY")
  - ssh fevermap@dev.fevermap.net -p 33100 -o StrictHostKeyChecking=no "cd /var/www/fevermap
    && make update-master && make run"
production:
  stage: deploy
  rules:
  - if: $CI_PROJECT_NAMESPACE == "fevermap" && $CI_COMMIT_TAG
  script:
  - |
    cat > "$(pwd)/post.data" << EOF
    env:
    - name: "TAG"
      value: "${CI_COMMIT_TAG}"
    - name: "COMMIT_ID"
      value: "${CI_COMMIT_SHORT_SHA}"
    EOF
  - curl -H "Content-Type:application/yaml" --data-binary @$(pwd)/post.data -X POST
    -k https://api.pro-eu-west-1.openshift.com/apis/build.openshift.io/v1/namespaces/fevermap-staging/buildconfigs/fevermap-release/webhooks/${OCP_WEBHOOK_TOKEN}/generic
pages:
  rules:
  - if: $CI_PROJECT_NAMESPACE == "fevermap" && $CI_COMMIT_BRANCH == "master"
  script:
  - hugo --source=website --destination=../public
  artifacts:
    paths:
    - public
  image: registry.gitlab.com/pages/hugo:0.40.1
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
